In [4]:
a=input("my name is")
b=input("my last name is")
d=b+''+a
print("my full name is",d)

my name is eya
my last name is dernaoui
my full name is  dernaoui eya

In [13]:
n=input("donner un nombre")
a=n
b=n+n
c=n+n+n
d=int(a)+int(b)+int(c)
print("the Result is",d)

donner un nombre5
the Result is 615

In [1]:
num = int(input("Enter a number: "))
if num %2==0:
    print("This is an even number.")
else:
    print("This is an odd number.")

Enter a number: 4
This is an even number.

In [10]:
for i in range (2000,3200):
    if i%7==0 and i%5 !=0:
        print(i)

2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996
3003
3017
3024
3031
3038
3052
3059
3066
3073
3087
3094
3101
3108
3122
3129
3136
3143
3157
3164
3171
3178
3192
3199

In [40]:
num = int(input("Enter a number: "))    
factorial = 1    
if num < 0:    
   print(" Factorial does not exist for negative numbers")    
elif num == 0:    
   print("The factorial of 0 is 1")    
else:    
   for i in range(1,num + 1):    
       factorial = factorial*i    
   print("The factorial of",num,"is",factorial)

Enter a number: 8
The factorial of 8 is 40320

In [55]:
def odd_values_string(str):
  result = "" 
  for i in range(len(str)):
    if i % 2 == 0:
      result = result + str[i]
  return result

a=print(odd_values_string('hello')+ odd_values_string('team'))

hlota

In [78]:
a=float(input("what is the price of the product "))
b=float(input("what is the pourcentage discoount? "))
i=float(input("what is the price of the product2"))
for i in range (200,500): 
    print(i)
c=float(input("what is the pourcentage dicount2 "))
d=float(input("what is the price of the product3 "))
print('(200<x)')
e=float(input("what is the pourcentage dicount3 "))

what is the price of the product 500
what is the pourcentage discoount? 50
what is the price of the product2450
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
what is the pourcentage dicount2 30
what is the price of the product3 120
(200<x)
what is the pourcentage dicount3 10

In [18]:
p=float(input("what is the price of the product "))
if p>=500:
    print('the pourcentage discount is',50)
elif p>=200 and p<=500:
    print('the pourcentage discount is',30)
elif p<=200:
    print('the pourcentage discount is',10)

what is the price of the product 400
the pourcentage discount is 30